name: gsheets_aki
description: A library for working with Google Sheets API v4.
  Manage your spreadsheets with gsheets in Dart.
version: 0.5.1
homepage: https://github.com/nobodyyu/gsheets_aki
repository: https://github.com/nobodyyu/gsheets_aki.git
issue_tracker: https://github.com/nobodyyu/gsheets_aki/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  meta: ^1.16.0
  collection: ^1.19.1

dev_dependencies:
  test: ^1.25.15
